### ISSUE TITLE
Tiny Builder should be published to official Dockerhub location

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/tiny-builder#2]
Once we've implemented #1 and we've verified that the changes look good, we should swap from the temporary GCR location to the official Dockerhub location for the tiny builder. Builders should get published to:
- paketobuildpacks/builder:tiny (for the latest version)
- paketobuildpacks/builder:<VERSION>-tiny (for specific versions)

**Note:** The concourse jobs for this builder should be switched off **BEFORE** this work is merged in.

**Comment by fg-j** [comment]
@kvedurmu Do we also want to be publishing this builder to cloudfoundry/cnb? Looks like existing automation pushes there: https://hub.docker.com/r/cloudfoundry/cnb/tags?page=1&name=tiny

**Comment by kvedurmu** [comment]
If we're pushing to cloudfoundry/cnb for the base builder, we should do it for Tiny as well. @martyspiewak can confirm.

**Comment by martyspiewak** [comment]
Yup that sounds right to me.
