### ISSUE TITLE
AnalysisError$ParsingError when migrating from 0.1.241 to 0.1.243

### ISSUE THREAD

**Issue by ledex** [paketo-buildpacks/tiny-builder#381]
## Expected Behavior
Builder should build native image.

## Current Behavior
Build terminates with error:
```
Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing org.springframework.boot.SpringApplication.createBeanDefinitionLoader(org.springframework.beans.factory.support.BeanDefinitionRegistry, java.lang.Object[]) 
```

## Possible Solution
Revert back to 0.1.241.

## Steps to Reproduce
N/a
We use the spring aot plugin in version 0.11.5.

## Motivations
This has halted the build-pipeline for all our products. We needed to revert from `:tiny` to `:0.1.241-tiny`.

**Comment by robdimsdale** [comment]
cc @paketo-buildpacks/java-buildpacks

**Comment by pivotal-david-osullivan** [comment]
We are looking into this issue which could be a problem with the latest GraalVM version (22.2), but adding the env var as detailed here #379 should allow the build to succeed

**Comment by ledex** [comment]
Thanks for the hint @pivotal-david-osullivan! I'll have a look at it.

**Comment by fg-j** [comment]
@ledex - How'd you fare with the workaround that @pivotal-david-osullivan proposed?

**Comment by robdimsdale** [comment]
I'm going to close this due to inactivity. Feel free to re-open if this is still an issue.
