### ISSUE TITLE
Procfile should be added to the Tiny builder as a stand alone buildpack

### ISSUE THREAD

**Issue by ForestEckhardt** [paketo-buildpacks/tiny-builder#42]
Procfile supports running on the Tiny stack which can be seen [here](https://github.com/paketo-buildpacks/procfile/blob/main/buildpack.toml). It would make sense to allow user to use the Tiny builder for small binaries that would run in such an environment.

**Comment by ForestEckhardt** [comment]
[RFC](https://github.com/paketo-buildpacks/builder/pull/49) address this issue.

**Comment by fg-j** [comment]
The RFC paketo-buildpacks/builder#49 has been approved. Reopening as this is now a relevant feature.
